parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    command_bus:
        middlewares:
            - Domain\Middlewares\CheckUserNameLengthMiddleware

dbal:
    connections:
        drift_users_api:
            driver: mysql
            host: 127.0.0.1
            port: 3306
            user: root
            password: ""
            dbname: drift_users_api

event_bus:
    exchanges:
        default: events_amqp
    router:
        _all: default
    async_pass_through: false
    async_adapter:
        adapter: amqp
        amqp:
            host: localhost

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controllers\:
        resource : "%app_path%/src/Controllers/*"
        tags:
            - {name: controller.service_arguments}

    Domain\Queries\Handlers\:
        resource : "%app_path%/src/Domain/Queries/Handlers/*"
        tags:
          - {name: "query_handler"}

    Domain\Commands\Handlers\:
        resource: "%app_path%/src/Domain/Commands/Handlers/*"
        tags:
          - {name: "command_handler"}

    Domain\Middlewares\:
        resource: "%app_path%/src/Domain/Middlewares/*"

    Domain\Repositories\InMemoryUserRepository:
    Domain\Repositories\DBALUserRepository:
    Domain\Repositories\ComposedUserRepository:

    Domain\Repositories\UserRepository:
        alias: Domain\Repositories\ComposedUserRepository